### ISSUE TITLE
DPI Setting

### ISSUE THREAD

**Issue by bluntwaco** [BeamRider/VRK-Releases#1]
Please fix the software DPI. The tabs located at the bottom cannot be accessed with the mouse from within the Windows Desktop. This is while not using the VR headset.
Thank you.

![Annotation 2020-04-23 135000](https://user-images.githubusercontent.com/4184268/80132379-97057900-8569-11ea-8c76-9f20b434cbff.png)

**Comment by BeamRider** [comment]
What is your monitor resolution? At what display scale?

**Comment by bluntwaco** [comment]
1920x1080
125% but even with recommended setting of 150% it's the same.

**Comment by BeamRider** [comment]
This should be handled with care because interfering with the GUI can have impact on rendering also.

**Comment by BeamRider** [comment]
Feature has been implemented and delivered in the 1.4.2.01 test version available on Discord.
Can you check it?

**Comment by BeamRider** [comment]
Released on v1.4.3.07
