### ISSUE TITLE
Image resolution

### ISSUE THREAD

**Issue by spit40** [BeamRider/VRK-Releases#13]
Can the resolution of images be higher? I have a Reverb and if I load a large image which is shrunk to fit the space the resize algorithm produces a very pixelly result rather than a readable resized  image.

**Comment by BeamRider** [comment]
Improvements on supersampling is ongoing, this should improve image readability on high resolution HMDs

**Comment by BeamRider** [comment]
This should have been fixed in public version 1.3.3.22
