### ISSUE TITLE
Enable cycle between Tabs

### ISSUE THREAD

**Issue by kaltokri** [BeamRider/VRK-Releases#15]
I want to propose a small enhancement.  I want to toggle between tabs with one button. At the moment I have to use Previous Tab and Next Tab.  Can you please add another Input Next Tab Cylcle, which switches to the first tab after the last tab is reached and the button is pressed again? Or an option in the settings to enable tab (and pages) cycling?

**Comment by MattCFII** [comment]
Agreed, this would be nice

**Comment by BeamRider** [comment]
Feature has been implemented and delivered in the 1.4.2.01 test version available on Discord.
Can you check it?

**Comment by BeamRider** [comment]
Released on v1.4.3.07
