### ISSUE TITLE
Tablet Buttons stop working until pen used again

### ISSUE THREAD

**Issue by ShortyJSW** [BeamRider/VRK-Releases#2]
VRK Version 1.3.3.20
Tablet Wacom Intuos S
DCS Build 2.5.6.45915

Frequently after using the tablet in game the tablet physical buttons to navigate stop working. I have to pick up the pen change a tab with it or use the onscreen previous and next arrows for them to work. I can then go a minute or so and it happens again.

**Comment by BeamRider** [comment]
Is the relative buttons feature disabled? Can you attach a log file?

**Comment by ShortyJSW** [comment]
Sure :-)
[vrkcpy.log](https://github.com/BeamRider/VRK-Releases/files/4533001/vrkcpy.log)

**Comment by BeamRider** [comment]
We have found that another user experienced a slightly different problem: in that case the pen stopped working for some time. 

To solve that case the procedure was:

1. create a VRK profile in Wacom Tablet Propertis with same parameters (this is unlikely to have resolved anything) 

2. Re-installing the Wacom driver.

**Comment by ShortyJSW** [comment]
Ok so I have played with this over the weekend and I think found a solution. I worked out this was happening to me with SRS running.
In the Settings Tab I changed the Global Setting 'Auto Refocus DCS' to 'OFF' and this seems to have fixed the problem for me.
