### ISSUE TITLE
Huion Pen Stylus freezes every 20secs until refocus

### ISSUE THREAD

**Issue by Moralomar** [BeamRider/VRK-Releases#3]
VRK: 1.3.3.20 with Custom Drivers Installed
DCS OpenBeta 2.5.6.47404
Windows 10
Nvidia GeForce Drivers: 441.87

Everything is working fine on the Desktop and I can set up my kneeboard pages with stylus and strokes working fine. Once I'm in DCS and try to use the stylus, the stylus cursor would freeze after 20secs. I can get the stylus cursor to work again by refocusing the kneeboard, but it'll freeze 20secs after.

**Comment by BeamRider** [comment]
Which VR HMD are you using Oculus or SteamVR?

If you are strapping the tablet to your leg it can be due to USB disconnection, but this also depends if you change tablet position between desktop and DCS usage.

**Comment by Moralomar** [comment]
I'm using the Oculus Quest with Link.
Tried it again and this issue didn't reoccur again. Guess I'll just continue to monitor.

**Comment by BeamRider** [comment]
I'm closing this for now, in case it happens again you can reopen it.
